<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanionPlantingKnowledgeExpansionSeeder extends Seeder
{
    /**
     * Add more companion planting knowledge for diverse crops
     * Focus: Salads, roots, solanaceae, cucurbits
     */
    public function run(): void
    {
        $now = \Carbon\Carbon::now();
        
        $companions = [
            // LETTUCE - Quick succession crop
            [
                'primary_crop' => 'Lettuce',
                'primary_crop_family' => 'Asteraceae',
                'companion_plant' => 'Radish',
                'companion_family' => 'Brassicaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Radishes mature before lettuce needs space. Deep taproot breaks soil. Flea beetles prefer radishes over lettuce (trap crop).',
                'planting_notes' => 'Sow radishes at same time as lettuce. Radishes harvest in 3-4 weeks, lettuce in 6-8 weeks. Radish leaves indicate flea beetle pressure.',
                'planting_timing' => 'Sow at same time as lettuce',
                'spacing_notes' => 'Mixed rows or alternating rows',
                'days_to_harvest_companion' => 25,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Charles Dowding intercropping trials',
                'confidence_score' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Lettuce',
                'primary_crop_family' => 'Asteraceae',
                'companion_plant' => 'Chervil',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Chervil provides light shade reducing lettuce bolting in summer. Attracts beneficial insects. Culinary herb.',
                'planting_notes' => 'Sow chervil with or 2 weeks after lettuce. Prefers partial shade so benefits from lettuce canopy. Harvest young leaves continuously.',
                'planting_timing' => 'Sow with or after lettuce',
                'spacing_notes' => 'Between rows or mixed',
                'days_to_harvest_companion' => 45,
                'quick_crop' => false,
                'seasonal_considerations' => null,
                'source' => 'Joy Larkcom salad intercropping',
                'confidence_score' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Lettuce',
                'primary_crop_family' => 'Asteraceae',
                'companion_plant' => 'Spring Onion',
                'companion_family' => 'Amaryllidaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Onion scent deters aphids and slugs. Different root zones. Quick harvest before lettuce matures.',
                'planting_notes' => 'Plant spring onion sets or modules between lettuce rows. Harvest as baby onions in 8-10 weeks.',
                'planting_timing' => 'Plant with lettuce',
                'spacing_notes' => 'Between rows, 5cm spacing',
                'days_to_harvest_companion' => 60,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'RHS companion planting trials',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // CARROTS - Root crop succession
            [
                'primary_crop' => 'Carrot',
                'primary_crop_family' => 'Apiaceae',
                'companion_plant' => 'Leek',
                'companion_family' => 'Amaryllidaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Leeks deter carrot root fly (strong scent masks carrots). Carrots deter leek moth and onion fly. Classic companion pairing.',
                'planting_notes' => 'Interplant rows: 1 row leeks, 2 rows carrots, 1 row leeks. Leeks planted as modules April-May, carrots direct sown.',
                'planting_timing' => 'Plant leeks at carrot sowing time',
                'spacing_notes' => 'Alternating rows',
                'days_to_harvest_companion' => 150,
                'quick_crop' => false,
                'seasonal_considerations' => 'Reduces carrot fly damage by 50-70% in trials',
                'source' => 'HDRA Heritage Seed Library trials',
                'confidence_score' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Carrot',
                'primary_crop_family' => 'Apiaceae',
                'companion_plant' => 'Rosemary',
                'companion_family' => 'Lamiaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Strong aroma deters carrot root fly. Perennial border plant. Culinary herb.',
                'planting_notes' => 'Plant rosemary as permanent border to carrot beds. Maintain as low hedge 30-40cm high. Hardy perennial.',
                'planting_timing' => 'Permanent perennial border',
                'spacing_notes' => 'Bed edges, 50cm spacing',
                'days_to_harvest_companion' => null,
                'quick_crop' => false,
                'seasonal_considerations' => 'Reduces carrot fly in edge rows',
                'source' => 'Bob Flowerdew companion planting',
                'confidence_score' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Carrot',
                'primary_crop_family' => 'Apiaceae',
                'companion_plant' => 'Chive',
                'companion_family' => 'Amaryllidaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Allium scent confuses carrot fly. Flowers attract hoverflies (aphid predators). Perennial.',
                'planting_notes' => 'Plant chive clumps every 60cm along carrot rows. Allow some to flower for beneficial insects.',
                'planting_timing' => 'Spring planting',
                'spacing_notes' => 'Along rows, 60cm intervals',
                'days_to_harvest_companion' => null,
                'quick_crop' => false,
                'seasonal_considerations' => null,
                'source' => 'Organic Gardening Magazine UK trials',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // TOMATOES - Greenhouse succession
            [
                'primary_crop' => 'Tomato',
                'primary_crop_family' => 'Solanaceae',
                'companion_plant' => 'Basil',
                'companion_family' => 'Lamiaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Basil repels aphids, whitefly, and tomato hornworm. May improve tomato flavour. Shares similar water/nutrient needs.',
                'planting_notes' => 'Plant basil modules at base of tomato plants (1 per plant). Both like warm greenhouse conditions. Pinch basil to keep bushy.',
                'planting_timing' => 'Plant with tomato transplants',
                'spacing_notes' => '1 basil per tomato plant',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Whitefly reduction observed in polytunnel trials',
                'source' => 'Garden Organic Ryton trials',
                'confidence_score' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Tomato',
                'primary_crop_family' => 'Solanaceae',
                'companion_plant' => 'French Marigold',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'French marigolds (Tagetes) deter whitefly and aphids. Root exudates suppress soil nematodes.',
                'planting_notes' => 'Plant French marigold modules at ends of tomato rows or 1 per plant. Choose compact varieties for greenhouse/polytunnel.',
                'planting_timing' => 'Plant with tomatoes',
                'spacing_notes' => 'Row ends or 1 per plant',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Nematode suppression documented',
                'source' => 'RHS Wisley tomato trials',
                'confidence_score' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Tomato',
                'primary_crop_family' => 'Solanaceae',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'relay',
                'benefits' => 'Fast-growing ground cover. Utilizes space and light before tomatoes grow tall. Shade-tolerant lettuce varieties work under tomatoes.',
                'planting_notes' => 'Sow cut-and-come-again lettuce when planting tomatoes. Harvest young leaves. Stops producing when tomatoes shade out (June-July).',
                'planting_timing' => 'Plant with tomato transplants',
                'spacing_notes' => 'Ground cover between tomatoes',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Charles Dowding polytunnel succession',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // COURGETTE - Cucurbit succession
            [
                'primary_crop' => 'Courgette',
                'primary_crop_family' => 'Cucurbitaceae',
                'companion_plant' => 'Nasturtium',
                'companion_family' => 'Tropaeolaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Nasturtiums attract aphids away from courgettes (trap crop). Ground cover suppresses weeds. Edible flowers and leaves.',
                'planting_notes' => 'Sow nasturtiums around courgette plants at transplant time (late May). Trailing varieties create living mulch.',
                'planting_timing' => 'Sow with courgette transplants',
                'spacing_notes' => 'Around plants, 30cm spacing',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Aphid reduction on courgettes',
                'source' => 'Joy Larkcom vegetable trials',
                'confidence_score' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Courgette',
                'primary_crop_family' => 'Cucurbitaceae',
                'companion_plant' => 'Radish',
                'companion_family' => 'Brassicaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'relay',
                'benefits' => 'Quick-growing crop harvested before courgettes expand. Marks planting positions. Breaks up soil.',
                'planting_notes' => 'Sow radishes when transplanting courgettes. Harvest before courgettes need full space (4-6 weeks).',
                'planting_timing' => 'Sow with courgettes',
                'spacing_notes' => 'Between plants',
                'days_to_harvest_companion' => 25,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'No-dig gardening principles',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // BEETROOT - Root vegetable
            [
                'primary_crop' => 'Beetroot',
                'primary_crop_family' => 'Amaranthaceae',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Lettuce shades soil keeping beetroot cool. Harvested before beetroot needs space. Different nutrient needs.',
                'planting_notes' => 'Sow lettuce between beetroot rows. Lettuce harvests in 6-8 weeks, beetroot in 10-12 weeks. Good for summer successions.',
                'planting_timing' => 'Sow lettuce with beetroot',
                'spacing_notes' => 'Between rows',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Succession planting guides UK',
                'confidence_score' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Beetroot',
                'primary_crop_family' => 'Amaranthaceae',
                'companion_plant' => 'Kohlrabi',
                'companion_family' => 'Brassicaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Both fast-growing. Similar spacing and timing. Kohlrabi matures slightly earlier providing staggered harvest.',
                'planting_notes' => 'Alternate rows or mix in same row. Both sow April-July for succession. Harvest kohlrabi at tennis ball size, beetroot continues.',
                'planting_timing' => 'Sow together',
                'spacing_notes' => 'Alternating rows or mixed',
                'days_to_harvest_companion' => 60,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Market garden intensive spacing',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // ROCKET - Quick salad crop
            [
                'primary_crop' => 'Rocket',
                'primary_crop_family' => 'Brassicaceae',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Mixed salad bed. Rocket grows faster than lettuce providing early harvest. Peppery leaves complement mild lettuce.',
                'planting_notes' => 'Mix rows or broadcast sow. Rocket ready in 3-4 weeks, lettuce in 6-8 weeks. Both cut-and-come-again.',
                'planting_timing' => 'Sow together',
                'spacing_notes' => 'Mixed rows or broadcast',
                'days_to_harvest_companion' => 25,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Salad leaf production systems',
                'confidence_score' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Rocket',
                'primary_crop_family' => 'Brassicaceae',
                'companion_plant' => 'Coriander',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Mixed herb bed. Both fast-growing. Coriander attracts beneficial insects. Different flavour profiles.',
                'planting_notes' => 'Sow in alternating rows or mix. Both bolt in summer heat - best for spring/autumn. Succession sow every 3 weeks.',
                'planting_timing' => 'Sow together spring/autumn',
                'spacing_notes' => 'Mixed or alternating rows',
                'days_to_harvest_companion' => 30,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Microgreen and baby leaf production',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // SPINACH - Leaf vegetable
            [
                'primary_crop' => 'Spinach',
                'primary_crop_family' => 'Amaranthaceae',
                'companion_plant' => 'Strawberry',
                'companion_family' => 'Rosaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Spinach provides ground cover between strawberry plants. Saponins in spinach may deter pests. Shares similar nutrient needs.',
                'planting_notes' => 'Sow winter spinach (Sept) in strawberry bed after fruiting. Harvest spinach spring, then strawberries fruit.',
                'planting_timing' => 'Sow Sept in strawberry beds',
                'spacing_notes' => 'Between strawberry plants',
                'days_to_harvest_companion' => 90,
                'quick_crop' => false,
                'seasonal_considerations' => null,
                'source' => 'Permaculture polyculture systems',
                'confidence_score' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Spinach',
                'primary_crop_family' => 'Amaranthaceae',
                'companion_plant' => 'Broad Bean',
                'companion_family' => 'Fabaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'relay',
                'benefits' => 'Spinach grows under young broad beans. Harvested before beans expand. Utilizes nitrogen from bean roots.',
                'planting_notes' => 'Sow spinach when broad beans are 10-15cm tall (April). Harvest spinach May-June before beans shade out.',
                'planting_timing' => 'Sow when beans 10-15cm tall',
                'spacing_notes' => 'Under bean plants',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => null,
                'source' => 'Charles Dowding spring succession',
                'confidence_score' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // LEEK - Allium for rotation
            [
                'primary_crop' => 'Leek',
                'primary_crop_family' => 'Amaryllidaceae',
                'companion_plant' => 'Celery',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Leeks deter celery fly and carrot fly. Celery deters leek moth and onion fly. Classic companion pairing for alliums and umbellifers.',
                'planting_notes' => 'Plant in alternating rows. Both transplanted May-June. Celery harvests earlier (Sept-Oct), leeks continue through winter.',
                'planting_timing' => 'Transplant together May-June',
                'spacing_notes' => 'Alternating rows',
                'days_to_harvest_companion' => 120,
                'quick_crop' => false,
                'seasonal_considerations' => 'Reduced pest damage in both crops',
                'source' => 'HDRA companion planting guide',
                'confidence_score' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'primary_crop' => 'Leek',
                'primary_crop_family' => 'Amaryllidaceae',
                'companion_plant' => 'Parsley',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'intercrop_type' => 'simultaneous',
                'benefits' => 'Parsley as edge crop. Different root zones. Parsley attracts hoverflies. Both winter hardy.',
                'planting_notes' => 'Plant parsley along leek bed edges. Both hardy through winter. Parsley provides greens when leeks dormant.',
                'planting_timing' => 'Plant parsley spring',
                'spacing_notes' => 'Bed edges, 20cm spacing',
                'days_to_harvest_companion' => 80,
                'quick_crop' => false,
                'seasonal_considerations' => null,
                'source' => 'Winter vegetable combinations UK',
                'confidence_score' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('companion_planting_knowledge')->insert($companions);

        $this->command->info('✅ Added ' . count($companions) . ' new companion planting entries');
    }
}
