<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CompanionPlantingKnowledgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $companions = [
            // ===== BRUSSELS SPROUTS =====
            [
                'primary_crop' => 'Brussels Sprouts',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Garlic',
                'companion_family' => 'Allium',
                'relationship_type' => 'beneficial',
                'benefits' => 'Strong aroma deters aphids, cabbage white butterflies, and other brassica pests. Different root zones minimize competition.',
                'planting_notes' => 'Plant garlic cloves in September-November around established Brussels sprouts. Garlic grows underneath the tall sprout plants, benefiting from partial shade during establishment.',
                'planting_timing' => 'Underplant garlic in autumn (Sept-Nov) beneath established sprouts',
                'spacing_notes' => 'Plant garlic cloves 10-15cm apart between Brussels sprout plants or along bed edges',
                'intercrop_type' => 'underplant',
                'days_to_harvest_companion' => 270, // Garlic: Sept planting → June harvest
                'quick_crop' => false,
                'seasonal_considerations' => 'Garlic requires vernalization (cold period) over winter. Brussels sprouts provide shade limiting autumn growth (beneficial), then garlic gets full sun in spring after sprouts are harvested. Perfect sequential timing.',
                'source' => 'Traditional companion planting knowledge + market garden practice',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Brussels Sprouts',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Nasturtium',
                'companion_family' => 'Tropaeolaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Acts as trap crop for aphids and cabbage white butterflies. Attracts beneficial insects. Edible flowers and leaves.',
                'planting_notes' => 'Plant along bed edges or between rows at transplant time. Nasturtium spreads and creates ground cover.',
                'planting_timing' => 'Plant at same time as Brussels sprout transplants (May-June)',
                'spacing_notes' => 'Bed edges or end of rows, 30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Frost tender - will die off in autumn. Harvest flowers and leaves throughout summer.',
                'source' => 'Organic gardening companion planting guides',
                'confidence_score' => 9,
            ],
            [
                'primary_crop' => 'Brussels Sprouts',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Radish',
                'companion_family' => 'Brassica',
                'relationship_type' => 'beneficial',
                'benefits' => 'Fast-growing intercrop. Deep taproot breaks up soil and improves structure. Can act as indicator plant for flea beetles.',
                'planting_notes' => 'Direct sow between Brussels sprout rows at transplant time. Harvest radishes within 3-4 weeks before sprouts need the space.',
                'planting_timing' => 'Sow when Brussels sprouts are transplanted (May-June)',
                'spacing_notes' => 'Between rows, 5cm spacing in row',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 25,
                'quick_crop' => true,
                'seasonal_considerations' => 'Early summer radishes bolt in heat - choose bolt-resistant varieties. Provides quick harvest before sprouts expand.',
                'source' => 'Market garden intercropping practice',
                'confidence_score' => 7,
            ],
            [
                'primary_crop' => 'Brussels Sprouts',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Fast-growing salad crop that utilizes space between young Brussels sprouts. Harvested before sprouts need full spacing.',
                'planting_notes' => 'Transplant or direct sow lettuce between Brussels sprout rows. Use bolt-resistant summer varieties.',
                'planting_timing' => 'Plant at Brussels sprout transplant time or 2 weeks after',
                'spacing_notes' => 'Between rows, 20-25cm spacing',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => 'Use summer varieties that tolerate heat. Harvest before sprouts expand in late summer.',
                'source' => 'Market garden succession planning',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Brussels Sprouts',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Dill',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Attracts beneficial insects including hoverflies (aphid predators), lacewings, and parasitic wasps. Improves pest control.',
                'planting_notes' => 'Sow dill along bed edges or end of rows. Allow some to flower to attract beneficials.',
                'planting_timing' => 'Sow in spring with or after Brussels sprout transplanting',
                'spacing_notes' => 'Bed edges, 20cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Self-seeds readily. Cut for culinary use or let flower for beneficial insects.',
                'source' => 'Beneficial insect habitat gardening',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Brussels Sprouts',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Thyme',
                'companion_family' => 'Lamiaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Aromatic herb deters cabbage white butterflies and flea beetles. Perennial ground cover.',
                'planting_notes' => 'Plant as permanent bed edge or between rows. Tolerates being walked on occasionally.',
                'planting_timing' => 'Plant in spring as perennial border to brassica beds',
                'spacing_notes' => 'Bed edges, 30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => null, // Perennial
                'quick_crop' => false,
                'seasonal_considerations' => 'Hardy perennial. Provides year-round protection and ground cover.',
                'source' => 'Aromatic pest deterrent companion planting',
                'confidence_score' => 7,
            ],
            
            // ===== CAULIFLOWER =====
            [
                'primary_crop' => 'Cauliflower',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Nasturtium',
                'companion_family' => 'Tropaeolaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Trap crop for aphids which can damage cauliflower curds. Attracts pollinators and beneficial insects.',
                'planting_notes' => 'Plant along bed edges or between rows. Monitor nasturtium for aphid buildup and remove if heavily infested.',
                'planting_timing' => 'Plant at cauliflower transplant time',
                'spacing_notes' => 'Bed edges or between rows, 30-40cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'For summer cauliflower. Frost kills nasturtium so not suitable for winter varieties.',
                'source' => 'Trap cropping strategy for aphid management',
                'confidence_score' => 9,
            ],
            [
                'primary_crop' => 'Cauliflower',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Quick intercrop between rows. Utilizes space while cauliflower is small. Harvested before cauliflower needs full spacing.',
                'planting_notes' => 'Transplant or sow lettuce between cauliflower rows at transplant time. Use appropriate seasonal varieties.',
                'planting_timing' => 'Plant with or shortly after cauliflower transplant',
                'spacing_notes' => 'Between rows, 20-25cm spacing',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => 'Summer cauliflower: use bolt-resistant lettuce. Winter cauliflower: use cold-hardy winter lettuce varieties.',
                'source' => 'Intensive market garden spacing',
                'confidence_score' => 9,
            ],
            [
                'primary_crop' => 'Cauliflower',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Spinach',
                'companion_family' => 'Amaranthaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Fast-growing leafy crop. Shallow roots don\'t compete with cauliflower. Harvested before cauliflower matures.',
                'planting_notes' => 'Sow spinach between rows at cauliflower transplant time. Cut-and-come-again harvest extends productivity.',
                'planting_timing' => 'Sow at cauliflower transplant time',
                'spacing_notes' => 'Between rows, broadcast or rows 10cm apart',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 40,
                'quick_crop' => true,
                'seasonal_considerations' => 'Better for autumn/winter cauliflower. Spinach bolts in summer heat.',
                'source' => 'Cool season intercropping',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Cauliflower',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Dill',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Attracts hoverflies, lacewings, and parasitic wasps that prey on aphids and caterpillars.',
                'planting_notes' => 'Sow along bed edges or in corners. Allow to flower for maximum beneficial insect attraction.',
                'planting_timing' => 'Sow in spring/early summer',
                'spacing_notes' => 'Bed edges, 20cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Self-seeds. Provides continual beneficial insect habitat throughout growing season.',
                'source' => 'Beneficial insect attraction strategy',
                'confidence_score' => 8,
            ],
            
            // ===== CABBAGE =====
            [
                'primary_crop' => 'Cabbage',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Nasturtium',
                'companion_family' => 'Tropaeolaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Trap crop for aphids and cabbage white butterflies. Ground cover reduces weeds.',
                'planting_notes' => 'Plant along bed edges or at row ends. Monitor for pest buildup.',
                'planting_timing' => 'Plant at cabbage transplant time',
                'spacing_notes' => 'Bed edges, 30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Best for spring/summer cabbage. Frost tender.',
                'source' => 'Trap cropping for pest management',
                'confidence_score' => 9,
            ],
            [
                'primary_crop' => 'Cabbage',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Quick salad crop harvested before cabbage heads form. Efficient use of space.',
                'planting_notes' => 'Intercrop between cabbage rows. Harvest before cabbage expands.',
                'planting_timing' => 'Plant at or after cabbage transplant',
                'spacing_notes' => 'Between rows, 20-25cm spacing',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => 'Match lettuce variety to season - bolt-resistant for summer, cold-hardy for winter.',
                'source' => 'Market garden intercropping',
                'confidence_score' => 9,
            ],
            [
                'primary_crop' => 'Cabbage',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Thyme',
                'companion_family' => 'Lamiaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Aromatic oils deter cabbage white butterflies and flea beetles. Perennial ground cover.',
                'planting_notes' => 'Establish as permanent bed edge plantings around cabbage beds.',
                'planting_timing' => 'Plant in spring as perennial border',
                'spacing_notes' => 'Bed edges, 30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => null,
                'quick_crop' => false,
                'seasonal_considerations' => 'Hardy perennial. Provides year-round pest deterrence.',
                'source' => 'Aromatic companion planting',
                'confidence_score' => 7,
            ],
            
            // ===== BROCCOLI / CALABRESE =====
            [
                'primary_crop' => 'Broccoli',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Lettuce',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Fast intercrop between rows. Harvested before broccoli needs full space.',
                'planting_notes' => 'Transplant or sow lettuce between broccoli rows.',
                'planting_timing' => 'Plant at broccoli transplant time',
                'spacing_notes' => 'Between rows, 20-25cm spacing',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 50,
                'quick_crop' => true,
                'seasonal_considerations' => 'Use seasonal varieties appropriate to timing.',
                'source' => 'Market garden practice',
                'confidence_score' => 9,
            ],
            [
                'primary_crop' => 'Broccoli',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Nasturtium',
                'companion_family' => 'Tropaeolaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Aphid protection and beneficial insect attraction.',
                'planting_notes' => 'Plant at bed edges or between rows.',
                'planting_timing' => 'Plant at broccoli transplant time',
                'spacing_notes' => 'Bed edges, 30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Frost tender - best for spring/summer broccoli.',
                'source' => 'Companion planting guides',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Broccoli',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Spinach',
                'companion_family' => 'Amaranthaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Quick growing intercrop. Different root depth minimizes competition.',
                'planting_notes' => 'Sow between rows at broccoli transplant time.',
                'planting_timing' => 'Sow at transplant time',
                'spacing_notes' => 'Between rows, broadcast or 10cm rows',
                'intercrop_type' => 'relay',
                'days_to_harvest_companion' => 40,
                'quick_crop' => true,
                'seasonal_considerations' => 'Best for autumn/winter broccoli. Spinach bolts in heat.',
                'source' => 'Cool season intercropping',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Broccoli',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Basil',
                'companion_family' => 'Lamiaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Aromatic pest deterrent. Attracts pollinators.',
                'planting_notes' => 'Plant at bed edges or between rows for summer broccoli.',
                'planting_timing' => 'Plant at broccoli transplant time',
                'spacing_notes' => 'Bed edges or between rows, 25-30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Frost tender - only for summer broccoli/calabrese.',
                'source' => 'Aromatic companion planting',
                'confidence_score' => 7,
            ],
            
            // ===== KALE =====
            [
                'primary_crop' => 'Kale',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Nasturtium',
                'companion_family' => 'Tropaeolaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Trap crop for aphids and cabbage pests. Edible flowers.',
                'planting_notes' => 'Plant at bed edges or between rows.',
                'planting_timing' => 'Plant at kale transplant time',
                'spacing_notes' => 'Bed edges, 30cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Best for spring/summer kale. Frost kills nasturtium.',
                'source' => 'Companion planting guides',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Kale',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Dill',
                'companion_family' => 'Apiaceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Attracts beneficial insects that control aphids and caterpillars.',
                'planting_notes' => 'Sow along bed edges. Allow to flower.',
                'planting_timing' => 'Sow in spring',
                'spacing_notes' => 'Bed edges, 20cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 60,
                'quick_crop' => false,
                'seasonal_considerations' => 'Self-seeds readily for continuous cover.',
                'source' => 'Beneficial insect habitat',
                'confidence_score' => 8,
            ],
            [
                'primary_crop' => 'Kale',
                'primary_crop_family' => 'Brassica',
                'companion_plant' => 'Chamomile',
                'companion_family' => 'Asteraceae',
                'relationship_type' => 'beneficial',
                'benefits' => 'Improves soil health. Attracts beneficial insects. Medicinal herb harvest.',
                'planting_notes' => 'Plant at bed edges or corners.',
                'planting_timing' => 'Spring planting',
                'spacing_notes' => 'Bed edges, 20-25cm spacing',
                'intercrop_type' => 'simultaneous',
                'days_to_harvest_companion' => 90,
                'quick_crop' => false,
                'seasonal_considerations' => 'Self-seeds. Provides ongoing benefits.',
                'source' => 'Medicinal herb companion planting',
                'confidence_score' => 6,
            ],
        ];
        
        foreach ($companions as &$companion) {
            $companion['created_at'] = $now;
            $companion['updated_at'] = $now;
        }
        
        DB::table('companion_planting_knowledge')->insert($companions);
        
        $this->command->info('✅ Inserted ' . count($companions) . ' companion planting knowledge entries');
    }
}
