<?php
return [
    'season' => [
        'last_frost' => env('LAST_FROST_DATE', '2025-05-10'), // Y-m-d
        'first_frost' => env('FIRST_FROST_DATE', '2025-10-15'),
        'timezone' => env('APP_TIMEZONE', 'UTC'),
    ],
    'crops' => [
        'lettuce_mix' => [
            'name' => 'Lettuce Mix',
            'family' => 'asteraceae',
            'methods' => ['direct','transplant'],
            'earliest_week' => 10,
            'latest_week' => 38,
            'succession_interval_weeks' => 2,
            'days_to_maturity' => 50,
            'frost_tolerance' => 'half-hardy',
            'row_spacing_cm' => 20,
            'in_row_spacing_cm' => 25,
            'transplant_lead_weeks' => 4,
            'notes' => 'Aim for steady weekly salad supply.'
        ],
        'carrot' => [
            'name' => 'Carrot',
            'family' => 'apiaceae',
            'methods' => ['direct'],
            'earliest_week' => 12,
            'latest_week' => 34,
            'succession_interval_weeks' => 3,
            'days_to_maturity' => 70,
            'frost_tolerance' => 'hardy',
            'row_spacing_cm' => 30,
            'in_row_spacing_cm' => 3,
            'notes' => 'Keep bed weed-free first 4 weeks.'
        ],
        'beetroot' => [
            'name' => 'Beetroot',
            'family' => 'amaranthaceae',
            'methods' => ['direct','transplant'],
            'earliest_week' => 14,
            'latest_week' => 32,
            'succession_interval_weeks' => 3,
            'days_to_maturity' => 55,
            'frost_tolerance' => 'half-hardy',
            'row_spacing_cm' => 30,
            'in_row_spacing_cm' => 6,
            'transplant_lead_weeks' => 3,
            'notes' => 'Cluster sow 3–4 seeds per cell.'
        ],
        'spring_onion' => [
            'name' => 'Spring Onion',
            'family' => 'alliaceae',
            'methods' => ['transplant'],
            'earliest_week' => 6,
            'latest_week' => 30,
            'succession_interval_weeks' => 4,
            'days_to_maturity' => 60,
            'frost_tolerance' => 'hardy',
            'row_spacing_cm' => 25,
            'in_row_spacing_cm' => 2,
            'transplant_lead_weeks' => 6,
            'notes' => 'Multi-sow 6–8 per cell.'
        ],
        'kale' => [
            'name' => 'Kale',
            'family' => 'brassicaceae',
            'methods' => ['transplant'],
            'earliest_week' => 12,
            'latest_week' => 26,
            'succession_interval_weeks' => 6,
            'days_to_maturity' => 65,
            'frost_tolerance' => 'hardy',
            'row_spacing_cm' => 45,
            'in_row_spacing_cm' => 45,
            'transplant_lead_weeks' => 5,
            'notes' => 'Netting against flea beetle early.'
        ],
        'courgette' => [
            'name' => 'Courgette',
            'family' => 'cucurbitaceae',
            'methods' => ['transplant'],
            'earliest_week' => 20,
            'latest_week' => 28,
            'succession_interval_weeks' => 4,
            'days_to_maturity' => 55,
            'frost_tolerance' => 'tender',
            'row_spacing_cm' => 90,
            'in_row_spacing_cm' => 90,
            'transplant_lead_weeks' => 4,
            'notes' => 'Do not plant before frost risk passes.'
        ],
        'spinach' => [
            'name' => 'Spinach',
            'family' => 'amaranthaceae',
            'methods' => ['direct','transplant'],
            'earliest_week' => 8,
            'latest_week' => 20,
            'succession_interval_weeks' => 3,
            'days_to_maturity' => 40,
            'frost_tolerance' => 'hardy',
            'row_spacing_cm' => 25,
            'in_row_spacing_cm' => 5,
            'transplant_lead_weeks' => 3,
            'notes' => 'Switch to chard after heat sets in.'
        ],
    ],
];
